export default [{
  name: 'JavaScript',
  src: 'ace/mode/javascript'
}, {
  name: 'Python',
  src: 'ace/mode/python'
}, {
  name: 'C/C++',
  src: 'ace/mode/c_cpp'
}, {
  name: 'Java',
  src: 'ace/mode/java'
}, {
  name: 'Objective-C',
  src: 'ace/mode/objectivec'
}, {
  name: 'Scala',
  src: 'ace/mode/scala'
}, {
  name: 'Go',
  src: 'ace/mode/golang'
}, {
  name: 'Haskell',
  src: 'ace/mode/haskell'
}, {
  name: 'Ruby',
  src: 'ace/mode/ruby'
}, {
  name: 'Swift',
  src: 'ace/mode/swift'
}, {
  name: 'C#',
  src: 'ace/mode/csharp'
}]
